---

- hosts: all_server

  tasks:

  - name: install hello-world 1-0 on 172.17.0.3
    yum:
      name: /home/saif/ansible-stuff/basic-example/src/hello-world-1-0.x86_64.rpm
      state: present
    when: ansible_default_ipv4['address']=='172.17.0.4'


  - name: install hello-world 2-0 on 172.17.0.4
    yum:
      name: /home/saif/ansible-stuff/basic-example/src/hello-world-2-0.x86_64.rpm
      state: present
    when: ansible_default_ipv4['address']=='172.17.0.4'



 
