---

- name: Install and configure tomcat
  hosts: web_server
  gather_facts: false

  tasks:

  - name: Updating repos
    yum:
      name: "*"
      state: latest

  - name: Installing required java
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: Downloading apache-tomcat
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.48/bin/apache-tomcat-9.0.48.tar.gz
      dest: /usr/local

  - name: Extracting apache-tomcat
    unarchive:
      src: /usr/local/apache-tomcat-9.0.48.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: Renaming apache-tomcat home
    command: mv /usr/local/apache-tomcat-9.0.48 /usr/local/apache-tomcat

  - name: Starting tomcat
    command: nohup /usr/local/apache-tomcat/bin/startup.sh &
